---

- hosts: raspberry_pi

  user: beirti
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - common
    - rpi_exporter
    - node_exporter

- hosts: monitoring_server
  user: beirti
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - monitoring_server